<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://example.photon/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://example.photon/" name="HelloService">
<types>
<xsd:schema>
<xsd:import namespace="http://example.photon/" schemaLocation="http://localhost:8082/SoapTest/HelloService?xsd=1"/>
</xsd:schema>
</types>
<message name="SayHello">
<part name="parameters" element="tns:SayHello"/>
</message>
<message name="SayHelloResponse">
<part name="parameters" element="tns:SayHelloResponse"/>
</message>
<portType name="SimpleWebService">
<operation name="SayHello">
<input wsam:Action="http://example.photon/SimpleWebService/SayHelloRequest" message="tns:SayHello"/>
<output wsam:Action="http://example.photon/SimpleWebService/SayHelloResponse" message="tns:SayHelloResponse"/>
</operation>
</portType>
<binding name="SimpleWebServicePortBinding" type="tns:SimpleWebService">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<operation name="SayHello">
<soap:operation soapAction=""/>
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
</operation>
</binding>
<service name="HelloService">
<port name="SimpleWebServicePort" binding="tns:SimpleWebServicePortBinding">
<soap:address location="http://localhost:8082/SoapTest/HelloService"/>
</port>
</service>
</definitions>